/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './*.html',
    './**/*.html',
    './assets/**/*.js',
    './**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        'brand-green': '#2d5c4f',
        'brand-green-dark': '#24473e',
        'brand-green-darker': '#1a332c',
        'brand-orange': '#f4a261',
        'brand-gold': '#D4AF37',
        'brand-white': '#F6F7F8',
        'brand-offblack': '#161616',
        'brand-sand': '#e4d5b9',
        'brand-cream': '#faf8f4',
        'steel': '#1e2a33',
        'steel-light': '#2c3e50',
        'steel-dark': '#151f27',
        'steel-border': '#34495e',
        'signal-red': '#e74c3c',
        'signal-red-dim': 'rgba(231, 76, 60, 0.15)',
        'grid-cyan': '#4fa3c4',
        'grid-cyan-dim': 'rgba(79, 163, 196, 0.12)',
        'text-off': '#e8ecef',
        'text-mid': '#94a3b8',
        'text-dim': '#64748b',
        'gold-accent': '#d4a94d',
        paper: '#d9d4c7',
        'dark-bg': '#0D1B2A',
        'card-bg': '#1B263B',
        'border-color': '#415A77',
        'text-light': '#E0E1DD',
        'accent-red': '#ef4444',
        'accent-blue': '#00B4D8',
        'accent-cyan': '#22d3ee',
        'accent-amber': '#f59e0b',
        'accent-emerald': '#10b981',
        'money-green': '#22c55e',
        'ipers-dark': '#07101e',
        'ipers-panel': '#0d1a2e',
        'ipers-deep': '#050c17',
        'ipers-border': '#1c2d47',
        'ipers-gold': '#c8a43c',
        'ipers-gold-lt': '#e0c060',
        'ipers-blue': '#4a7fa5',
        'ipers-blue-lt': '#6ba3c8',
        'ipers-red': '#c24b4b',
        'ipers-red-lt': '#e05a5a',
        'ipers-sand': '#cec9c0',
        'ipers-sand-dim': '#8a9bb0',
        'exhibit-dark': '#0d1a12',
        'exhibit-panel': '#112218',
        'exhibit-border': '#1e3a29',
        vault: '#141b2d',
        'vault-light': '#1c2540',
        'vault-dark': '#0e1320',
        'vault-border': '#2a3352',
        parchment: '#c4973a',
        'parchment-dim': 'rgba(196, 151, 58, 0.12)',
        'bio-violet': '#7c6fae',
        'bio-violet-dim': 'rgba(124, 111, 174, 0.12)',
        rust: '#b94a3f',
        'rust-dim': 'rgba(185, 74, 63, 0.15)',
        'text-warm': '#e5e2dc',
      },
      fontFamily: {
        sans: ['system-ui', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'sans-serif'],
        serif: ['Georgia', 'Cambria', '"Times New Roman"', 'serif'],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
      },
    },
  },
};
