module.exports = {
  content: ["./**/*.{html,js}"],
  theme: {
    extend: {
      colors: {
        'brand-green': '#2d5c4f',
        'brand-green-dark': '#24473e',
        'brand-green-darker': '#1a332c',
        'brand-orange': '#f4a261',
        'brand-gold': '#D4AF37',
        'brand-white': '#F6F7F8',
        'brand-offblack': '#161616',
        'brand-sand': '#e4d5b9',
        'brand-cream': '#faf8f4',
        'dark-bg': '#0f172a',
        'card-bg': '#1f2937',
        'border-color': '#374151',
        'text-light': '#e5e7eb',
        'text-mid': '#9ca3af',
        'text-dim': '#6b7280',
        'text-off': '#cbd5e1',
        'text-warm': '#f5e6c8',
        'accent': '#D4AF37',
        'accent-burnished-gold': '#c58a2a',
        'accent-red': '#ef4444',
        'accent-blue': '#3b82f6',
        'accent-cyan': '#06b6d4',
        'accent-amber': '#f59e0b',
        'bio-violet': '#7c3aed',
        'bio-violet-dim': '#5b21b6',
        'ipers-dark': '#0f2231',
        'ipers-panel': '#173247',
        'ipers-border': '#2f4e69',
        'ipers-blue': '#3b82f6',
        'ipers-blue-lt': '#93c5fd',
        'ipers-gold': '#D4AF37',
        'ipers-gold-lt': '#f2d98a',
        'ipers-red': '#dc2626',
        'ipers-red-lt': '#fca5a5',
        'ipers-sand': '#e4d5b9',
        'ipers-deep': '#102a43',
        'vault': '#1b4332',
        'vault-dark': '#081c15',
        'vault-border': '#2d6a4f',
        'steel': '#475569',
        'steel-dark': '#1e293b',
        'steel-border': '#64748b',
        parchment: '#f8f1df',
        'parchment-dim': '#e9dcc2',
        rust: '#b45309',
        'rust-dim': '#92400e',
        'signal-red': '#b91c1c',
        'signal-red-dim': '#7f1d1d',
        'money-green': '#16a34a',
        'grid-cyan': '#22d3ee',
        'grid-cyan-dim': '#0891b2',
        'custom-light': '#f8fafc',
        'card-dark': '#111827',
        'gold-accent': '#D4AF37',
        'exhibit-dark': '#020617',
        'exhibit-panel': '#0f172a',
        'exhibit-border': '#334155'
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        serif: ['Lora', 'Georgia', 'serif']
      }
    }
  },
  plugins: []
};
